local map = vim.keymap.set

map("n", "<Esc>", "<cmd>nohlsearch<CR>")
map("n", "<leader>w", "<cmd>write<CR>", { desc = "Write file" })
map("n", "<leader>q", "<cmd>quit<CR>", { desc = "Quit window" })
map("n", "<leader>x", "<cmd>bdelete<CR>", { desc = "Close buffer" })
map("n", "<leader>bd", "<cmd>bdelete<CR>", { desc = "Close buffer" })
map("n", "<leader>bo", "<cmd>BufferLineCloseOthers<CR>", { desc = "Close other buffers" })
map("n", "<S-l>", "<cmd>BufferLineCycleNext<CR>", { desc = "Next buffer" })
map("n", "<S-h>", "<cmd>BufferLineCyclePrev<CR>", { desc = "Previous buffer" })

map("n", "<F2>", vim.lsp.buf.rename, { desc = "Rename symbol" })
map("n", "<F3>", "<cmd>Telescope find_files<CR>", { desc = "Find files" })
map("n", "<F4>", "<cmd>Telescope buffers<CR>", { desc = "Find buffers" })
map("n", "<F5>", "<cmd>Neotree toggle<CR>", { desc = "Toggle file tree" })
map("n", "<F6>", "<cmd>Trouble diagnostics toggle<CR>", { desc = "Diagnostics list" })
map("n", "<F7>", "<cmd>Gitsigns prev_hunk<CR>", { desc = "Previous git hunk" })
map("n", "<F8>", "<cmd>Gitsigns next_hunk<CR>", { desc = "Next git hunk" })
map("n", "<F9>", "<cmd>Neogit<CR>", { desc = "Neogit" })
map("n", "<F10>", "<cmd>DiffviewOpen<CR>", { desc = "Open git diff view" })
map("n", "<F12>", vim.lsp.buf.definition, { desc = "Go to definition" })

map("n", "<leader>wh", "<C-w><C-h>", { desc = "Focus left window" })
map("n", "<leader>wj", "<C-w><C-j>", { desc = "Focus lower window" })
map("n", "<leader>wk", "<C-w><C-k>", { desc = "Focus upper window" })
map("n", "<leader>wl", "<C-w><C-l>", { desc = "Focus right window" })

map("n", "<leader>e", "<cmd>Neotree toggle<CR>", { desc = "Toggle file tree" })
map("n", "<leader>ff", "<cmd>Telescope find_files<CR>", { desc = "Find files" })
map("n", "<leader>fg", "<cmd>Telescope live_grep<CR>", { desc = "Live grep" })
map("n", "<leader>fb", "<cmd>Telescope buffers<CR>", { desc = "Find buffers" })
map("n", "<leader>fh", "<cmd>Telescope help_tags<CR>", { desc = "Help tags" })
map("n", "<leader>fr", "<cmd>Telescope oldfiles<CR>", { desc = "Recent files" })
map("n", "<leader>fc", "<cmd>Telescope current_buffer_fuzzy_find<CR>", { desc = "Search current buffer" })
map("n", "<leader>fd", function()
  require("telescope.builtin").find_files({ cwd = vim.fn.expand("%:p:h") })
end, { desc = "Find near current file" })

local copy_to_clipboard = function(value, label)
  vim.fn.setreg("+", value)
  vim.notify("Copied " .. label .. ": " .. value)
end

map("n", "<S-F5>", function()
  copy_to_clipboard(vim.fn.expand("%:p"), "file path")
end, { desc = "Copy file path" })

map("n", "<S-F6>", function()
  copy_to_clipboard(vim.fn.expand("%:p") .. ":" .. vim.fn.line("."), "file path and line")
end, { desc = "Copy file path and line" })

map("n", "<leader>yf", function()
  copy_to_clipboard(vim.fn.expand("%:t"), "file name")
end, { desc = "Copy file name" })

map("n", "<leader>yp", function()
  copy_to_clipboard(vim.fn.expand("%:p"), "file path")
end, { desc = "Copy file path" })

map("n", "<leader>yr", function()
  copy_to_clipboard(vim.fn.expand("%:.") .. ":" .. vim.fn.line("."), "relative path and line")
end, { desc = "Copy relative path and line" })

map("n", "<leader>yl", function()
  copy_to_clipboard(vim.fn.expand("%:p") .. ":" .. vim.fn.line("."), "file path and line")
end, { desc = "Copy file path and line" })

map("n", "<leader>gg", "<cmd>Neogit<CR>", { desc = "Neogit" })
map("n", "<leader>gd", "<cmd>DiffviewOpen<CR>", { desc = "Open git diff view" })
map("n", "<leader>gD", "<cmd>DiffviewClose<CR>", { desc = "Close git diff view" })
map("n", "<leader>gH", "<cmd>DiffviewFileHistory %<CR>", { desc = "Current file git history" })
map("n", "<leader>gL", "<cmd>DiffviewFileHistory<CR>", { desc = "Repository git history" })
map("n", "<leader>gn", "<cmd>Gitsigns next_hunk<CR>", { desc = "Next git hunk" })
map("n", "<leader>gp", "<cmd>Gitsigns prev_hunk<CR>", { desc = "Previous git hunk" })
map("n", "<leader>gh", "<cmd>Gitsigns preview_hunk<CR>", { desc = "Preview git hunk" })
map("n", "<leader>gs", "<cmd>Gitsigns stage_hunk<CR>", { desc = "Stage git hunk" })
map("n", "<leader>gr", "<cmd>Gitsigns reset_hunk<CR>", { desc = "Reset git hunk" })
map("n", "<leader>gb", "<cmd>Gitsigns blame_line<CR>", { desc = "Blame current line" })
map("n", "<leader>tt", "<cmd>terminal<CR>", { desc = "Terminal" })

map({ "n", "x", "o" }, "<leader>j", function()
  require("flash").jump()
end, { desc = "Flash jump" })
map({ "n", "x", "o" }, "<leader>J", function()
  require("flash").treesitter()
end, { desc = "Flash treesitter" })

map("n", "<leader>cf", function()
  require("conform").format({ async = true, lsp_fallback = true })
end, { desc = "Format buffer" })

map("n", "<leader>ll", function()
  require("lint").try_lint()
end, { desc = "Run linters" })

map("n", "<leader>ha", function()
  require("harpoon"):list():add()
end, { desc = "Harpoon add file" })
map("n", "<leader>hh", function()
  local harpoon = require("harpoon")
  harpoon.ui:toggle_quick_menu(harpoon:list())
end, { desc = "Harpoon menu" })
map("n", "<leader>h1", function() require("harpoon"):list():select(1) end, { desc = "Harpoon file 1" })
map("n", "<leader>h2", function() require("harpoon"):list():select(2) end, { desc = "Harpoon file 2" })
map("n", "<leader>h3", function() require("harpoon"):list():select(3) end, { desc = "Harpoon file 3" })
map("n", "<leader>h4", function() require("harpoon"):list():select(4) end, { desc = "Harpoon file 4" })

map("n", "<leader>dd", "<cmd>Trouble diagnostics toggle<CR>", { desc = "Diagnostics list" })
map("n", "<leader>dD", "<cmd>Trouble diagnostics toggle filter.buf=0<CR>", { desc = "Buffer diagnostics" })
map("n", "<leader>dt", "<cmd>Trouble symbols toggle focus=false<CR>", { desc = "Trouble symbols" })
map("n", "<leader>dq", "<cmd>Trouble qflist toggle<CR>", { desc = "Quickfix list" })

map("n", "<leader>sr", "<cmd>Spectre<CR>", { desc = "Search and replace" })
map("n", "<leader>sw", "<cmd>lua require('spectre').open_visual({select_word=true})<CR>", { desc = "Replace current word" })
